<rss version="0.92"><channel><title>CloudRouter Issues</title><link>https://cloudrouter.atlassian.net/secure/IssueNavigator.jspa?reset=true&jqlQuery=filter+%3D+%22CR-2+bugs%22+AND+%28status+%3D+Resolved+OR+status+%3D+Closed%29+ORDER+BY+created+ASC</link><description>An XML representation of a search request</description><language>en-us</language><issue start="0" end="19" total="19"/><build-info><version>6.5-OD-08-001</version><build-number>65007</build-number><build-date>01-07-2015</build-date></build-info><item><title>[CR-10] Include mininet</title><link>https://cloudrouter.atlassian.net/browse/CR-10</link><project id="10002" key="CR">CloudRouter Project</project><description/><environment/><key id="10016">CR-10</key><summary>Include mininet</summary><type id="1" iconUrl="https://cloudrouter.atlassian.net/images/icons/issuetypes/bug.png">Bug</type><priority id="3" iconUrl="https://cloudrouter.atlassian.net/images/icons/priorities/medium.png">Medium</priority><status id="5" iconUrl="https://cloudrouter.atlassian.net/images/icons/statuses/resolved.png" description="A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.">Resolved</status><statusCategory id="3" key="done" colorName="green"/><resolution id="1">Fixed</resolution><assignee username="-1">Unassigned</assignee><reporter username="ckannan">Chandrasekar Kannan</reporter><labels>
                    </labels><created>Wed, 18 Feb 2015 10:57:31 +1000</created><updated>Thu, 9 Jul 2015 03:54:59 +1000</updated><resolved>Thu, 9 Jul 2015 03:54:59 +1000</resolved><component>Distribution</component><due/><votes>0</votes><watches>2</watches><comments><comment id="10021" author="juliettkilotango" created="Wed, 18 Feb 2015 10:59:32 +1000"><p>It is packaged, but not yet submitted for Fedora inclusion.</p></comment><comment id="11010" author="ckannan" created="Thu, 9 Jul 2015 03:54:55 +1000"><p>done. we have mininet working</p></comment></comments><attachments>
                    </attachments><subtasks>
                    </subtasks><customfields><customfield id="customfield_10025" key="com.atlassian.jira.plugin.system.customfieldtypes:textfield"><customfieldname>External issue ID</customfieldname><customfieldvalues><customfieldvalue>10</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10012" key="com.pyxis.greenhopper.jira:gh-lexo-rank"><customfieldname>Rank</customfieldname><customfieldvalues><customfieldvalue>0|i0003j:</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10200" key="com.atlassian.jira.plugin.system.customfieldtypes:select"><customfieldname>Target Milestone</customfieldname><customfieldvalues><customfieldvalue key="10201">CR-2</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10023" key="com.atlassian.bonfire.plugin:bonfire-testing-status-cft"><customfieldname>Testing Status</customfieldname><customfieldvalues></customfieldvalues></customfield><customfield id="customfield_10000" key="com.atlassian.jira.ext.charting:firstresponsedate"><customfieldname>[CHART] Date of First Response</customfieldname><customfieldvalues><customfieldvalue>Tue, 17 Feb 2015 16:59:32 -0800</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10001" key="com.atlassian.jira.ext.charting:timeinstatus"><customfieldname>[CHART] Time in Status</customfieldname><customfieldvalues></customfieldvalues></customfield></customfields></item><item><title>[CR-27] Rebase on Fedora 22 once it is available</title><link>https://cloudrouter.atlassian.net/browse/CR-27</link><project id="10002" key="CR">CloudRouter Project</project><description><p>Fedora 22 is due to be released on 2015-05-19. Fedora 20 support will end one month later. OpenDaylight Lithium is due to ship on 2015-06-25, with Java 8 support. Since Fedora &gt; 20 does not include Java 7, as an interim measure we should rebase on Fedora 22 as soon as it ships, and use copr for Java 7 until OpenDaylight Lithium ships.</p></description><environment/><key id="10033">CR-27</key><summary>Rebase on Fedora 22 once it is available</summary><type id="4" iconUrl="https://cloudrouter.atlassian.net/images/icons/issuetypes/improvement.png">Improvement</type><priority id="1" iconUrl="https://cloudrouter.atlassian.net/images/icons/priorities/highest.png">Highest</priority><status id="5" iconUrl="https://cloudrouter.atlassian.net/images/icons/statuses/resolved.png" description="A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.">Resolved</status><statusCategory id="3" key="done" colorName="green"/><resolution id="1">Fixed</resolution><assignee username="jturner">Jay Turner</assignee><reporter username="dfj">David Jorm</reporter><labels>
                    </labels><created>Mon, 9 Mar 2015 14:49:38 +1000</created><updated>Mon, 13 Jul 2015 09:56:59 +1000</updated><resolved>Mon, 13 Jul 2015 09:56:59 +1000</resolved><component>Distribution</component><due/><votes>0</votes><watches>2</watches><comments><comment id="10026" author="dfj" created="Tue, 10 Mar 2015 20:37:29 +1000"><p>ODL Java 8 support can be tracked via this bug: <a href="https://bugs.opendaylight.org/show_bug.cgi?id=2625" class="external-link" rel="nofollow">https://bugs.opendaylight.org/show_bug.cgi?id=2625</a></p></comment><comment id="11032" author="ckannan" created="Sat, 11 Jul 2015 05:44:09 +1000"><p>if this is not talking about docker images - then we can resolve this bug</p></comment><comment id="11042" author="dfj" created="Mon, 13 Jul 2015 09:56:53 +1000"><p>My original concern when filing this issue was upgrading the "main" image distribution. Docker images have historically been released asynchronous to CloudRouter's normal product schedule. Therefore I think this one can be resolved.</p></comment></comments><issuelinks><issuelinktype id="10000"><name>Blocks</name><inwardlinks description="is blocked by"><issuelink><issuekey id="10211">DOCKER-7</issuekey></issuelink></inwardlinks></issuelinktype></issuelinks><attachments>
                    </attachments><subtasks><subtask id="10208">CR-65</subtask><subtask id="10210">CR-67</subtask></subtasks><customfields><customfield id="customfield_10025" key="com.atlassian.jira.plugin.system.customfieldtypes:textfield"><customfieldname>External issue ID</customfieldname><customfieldvalues><customfieldvalue>27</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10012" key="com.pyxis.greenhopper.jira:gh-lexo-rank"><customfieldname>Rank</customfieldname><customfieldvalues><customfieldvalue>0|i0007b:</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10200" key="com.atlassian.jira.plugin.system.customfieldtypes:select"><customfieldname>Target Milestone</customfieldname><customfieldvalues><customfieldvalue key="10201">CR-2</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10023" key="com.atlassian.bonfire.plugin:bonfire-testing-status-cft"><customfieldname>Testing Status</customfieldname><customfieldvalues></customfieldvalues></customfield><customfield id="customfield_10000" key="com.atlassian.jira.ext.charting:firstresponsedate"><customfieldname>[CHART] Date of First Response</customfieldname><customfieldvalues><customfieldvalue>Fri, 10 Jul 2015 12:44:09 -0700</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10001" key="com.atlassian.jira.ext.charting:timeinstatus"><customfieldname>[CHART] Time in Status</customfieldname><customfieldvalues></customfieldvalues></customfield></customfields></item><item><title>[CR-47] Add custom SSH banner</title><link>https://cloudrouter.atlassian.net/browse/CR-47</link><project id="10002" key="CR">CloudRouter Project</project><description><p>$</p>
{summary}</description><environment/><key id="10123">CR-47</key><summary>Add custom SSH banner</summary><type id="4" iconUrl="https://cloudrouter.atlassian.net/images/icons/issuetypes/improvement.png">Improvement</type><priority id="3" iconUrl="https://cloudrouter.atlassian.net/images/icons/priorities/medium.png">Medium</priority><status id="6" iconUrl="https://cloudrouter.atlassian.net/images/icons/statuses/closed.png" description="The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.">Closed</status><statusCategory id="3" key="done" colorName="green"/><resolution id="1">Fixed</resolution><assignee username="-1">Unassigned</assignee><reporter username="abn">Arun Neelicattu</reporter><labels>
                    </labels><created>Fri, 3 Apr 2015 05:52:57 +1000</created><updated>Sat, 11 Jul 2015 06:52:41 +1000</updated><resolved>Sat, 11 Jul 2015 06:52:41 +1000</resolved><component>cloudrouter-release</component><due/><votes>0</votes><watches>4</watches><comments><comment id="10125" author="dfj" created="Sat, 4 Apr 2015 09:55:08 +1000"><p>Should this issue and <a href="https://cloudrouter.atlassian.net/browse/CR-48" title="Boot menu should show CloudRouter not ${BASE_OS}" class="issue-link" data-issue-key="CR-48"><del>CR-48</del></a> be addressed via the cloudrouter-release package, or is a new package required?</p></comment><comment id="10126" author="abn" created="Sat, 4 Apr 2015 10:10:29 +1000"><p>Not having this in the release package would be the way to go since the release package could be installed on a non-cloudrouter instance for getting the repositories installed. The other option is to split out release into release and repo with the latter being a dependency of the former. If this is done, we can include banner replacement, branding, issues fixing etc in release and use it only for official images.</p></comment><comment id="11013" author="ckannan" created="Thu, 9 Jul 2015 04:40:33 +1000"><p><a href="http://pastebin.com/raw.php?i=M87cB7j5" class="external-link" rel="nofollow">http://pastebin.com/raw.php?i=M87cB7j5</a> made an ascii art in case we want to use it</p></comment><comment id="11017" author="ckannan" created="Thu, 9 Jul 2015 06:20:59 +1000"><p><a href="https://github.com/cloudrouter/cloudrouter/pull/105" class="external-link" rel="nofollow">https://github.com/cloudrouter/cloudrouter/pull/105</a></p></comment><comment id="11034" author="jturner" created="Sat, 11 Jul 2015 06:52:41 +1000"><p>All fixed <img class="emoticon" src="https://cloudrouter.atlassian.net/images/icons/emoticons/smile.gif" height="16" width="16" align="absmiddle" alt="" border="0"/></p></comment></comments><attachments>
                    </attachments><subtasks>
                    </subtasks><customfields><customfield id="customfield_10012" key="com.pyxis.greenhopper.jira:gh-lexo-rank"><customfieldname>Rank</customfieldname><customfieldvalues><customfieldvalue>0|i000e7:</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10200" key="com.atlassian.jira.plugin.system.customfieldtypes:select"><customfieldname>Target Milestone</customfieldname><customfieldvalues><customfieldvalue key="10201">CR-2</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10023" key="com.atlassian.bonfire.plugin:bonfire-testing-status-cft"><customfieldname>Testing Status</customfieldname><customfieldvalues></customfieldvalues></customfield><customfield id="customfield_10000" key="com.atlassian.jira.ext.charting:firstresponsedate"><customfieldname>[CHART] Date of First Response</customfieldname><customfieldvalues><customfieldvalue>Fri, 3 Apr 2015 16:55:08 -0700</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10001" key="com.atlassian.jira.ext.charting:timeinstatus"><customfieldname>[CHART] Time in Status</customfieldname><customfieldvalues></customfieldvalues></customfield></customfields></item><item><title>[CR-48] Boot menu should show CloudRouter not ${BASE_OS}</title><link>https://cloudrouter.atlassian.net/browse/CR-48</link><project id="10002" key="CR">CloudRouter Project</project><description><p>$</p>
{summary}</description><environment/><key id="10124">CR-48</key><summary>Boot menu should show CloudRouter not ${BASE_OS}</summary><type id="1" iconUrl="https://cloudrouter.atlassian.net/images/icons/issuetypes/bug.png">Bug</type><priority id="3" iconUrl="https://cloudrouter.atlassian.net/images/icons/priorities/medium.png">Medium</priority><status id="5" iconUrl="https://cloudrouter.atlassian.net/images/icons/statuses/resolved.png" description="A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.">Resolved</status><statusCategory id="3" key="done" colorName="green"/><resolution id="1">Fixed</resolution><assignee username="-1">Unassigned</assignee><reporter username="abn">Arun Neelicattu</reporter><labels>
                    </labels><created>Fri, 3 Apr 2015 05:53:37 +1000</created><updated>Tue, 7 Jul 2015 03:42:59 +1000</updated><resolved>Tue, 7 Jul 2015 03:42:59 +1000</resolved><component>cloudrouter-release</component><due/><votes>0</votes><watches>2</watches><comments><comment id="11000" author="ckannan" created="Tue, 7 Jul 2015 03:42:48 +1000"><p>boot menu shows cloudrouter. resolving.</p></comment></comments><attachments><attachment id="10200" name="Screenshot from 2015-07-06 10-42-11.png" size="44523" author="ckannan" created="Tue, 7 Jul 2015 03:42:37 +1000"/></attachments><subtasks>
                    </subtasks><customfields><customfield id="customfield_10012" key="com.pyxis.greenhopper.jira:gh-lexo-rank"><customfieldname>Rank</customfieldname><customfieldvalues><customfieldvalue>0|i000ef:</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10200" key="com.atlassian.jira.plugin.system.customfieldtypes:select"><customfieldname>Target Milestone</customfieldname><customfieldvalues><customfieldvalue key="10201">CR-2</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10023" key="com.atlassian.bonfire.plugin:bonfire-testing-status-cft"><customfieldname>Testing Status</customfieldname><customfieldvalues></customfieldvalues></customfield><customfield id="customfield_10000" key="com.atlassian.jira.ext.charting:firstresponsedate"><customfieldname>[CHART] Date of First Response</customfieldname><customfieldvalues><customfieldvalue>Mon, 6 Jul 2015 10:42:48 -0700</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10001" key="com.atlassian.jira.ext.charting:timeinstatus"><customfieldname>[CHART] Time in Status</customfieldname><customfieldvalues></customfieldvalues></customfield></customfields></item><item><title>[CR-60] CloudRouter Images when launched on google cloud fails during cloud-init</title><link>https://cloudrouter.atlassian.net/browse/CR-60</link><project id="10002" key="CR">CloudRouter Project</project><description><p><a href="https://gist.githubusercontent.com/ckannan/b366ac67ee1ccccdabef/raw/c4d8e3f6b12f64cc8cee8627b96af5dfe1e9bd60/gistfile1.txt" class="external-link" rel="nofollow">https://gist.githubusercontent.com/ckannan/b366ac67ee1ccccdabef/raw/c4d8e3f6b12f64cc8cee8627b96af5dfe1e9bd60/gistfile1.txt</a></p></description><environment/><key id="10200">CR-60</key><summary>CloudRouter Images when launched on google cloud fails during cloud-init</summary><type id="1" iconUrl="https://cloudrouter.atlassian.net/images/icons/issuetypes/bug.png">Bug</type><priority id="1" iconUrl="https://cloudrouter.atlassian.net/images/icons/priorities/highest.png">Highest</priority><status id="5" iconUrl="https://cloudrouter.atlassian.net/images/icons/statuses/resolved.png" description="A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.">Resolved</status><statusCategory id="3" key="done" colorName="green"/><resolution id="1">Fixed</resolution><assignee username="ckannan">Chandrasekar Kannan</assignee><reporter username="ckannan">Chandrasekar Kannan</reporter><labels>
                    </labels><created>Tue, 14 Apr 2015 07:43:50 +1000</created><updated>Tue, 7 Jul 2015 03:45:02 +1000</updated><resolved>Tue, 7 Jul 2015 03:45:02 +1000</resolved><component>image</component><due/><votes>0</votes><watches>1</watches><comments><comment id="10200" author="ckannan" created="Tue, 14 Apr 2015 07:58:00 +1000"><p>Most articles on the web suggest to disable NetworkManager and to have NOZEROCONF=yes on /etc/sysconfig/network</p></comment><comment id="10201" author="ckannan" created="Tue, 14 Apr 2015 07:58:27 +1000"><p><a href="https://git.fedorahosted.org/cgit/spin-kickstarts.git/tree/fedora-cloud-base.ks?h=f21#n142" class="external-link" rel="nofollow">https://git.fedorahosted.org/cgit/spin-kickstarts.git/tree/fedora-cloud-base.ks?h=f21#n142</a><br/>
<a href="https://git.fedorahosted.org/cgit/spin-kickstarts.git/tree/fedora-cloud-base.ks?h=f21#n29" class="external-link" rel="nofollow">https://git.fedorahosted.org/cgit/spin-kickstarts.git/tree/fedora-cloud-base.ks?h=f21#n29</a></p></comment><comment id="10604" author="ckannan" created="Thu, 21 May 2015 04:51:47 +1000"><p>further investigation reveals this is due to cloud-init package that's on Fedora 20. Fedora 21 and above has cloud-init 0.7.5 or greater which has the GCE support built-in. </p></comment><comment id="11001" author="ckannan" created="Tue, 7 Jul 2015 03:44:57 +1000"><p>Tested with updated Fedora 22 based cloudrouter 2 images. Output here <a href="https://gist.githubusercontent.com/ckannan/59c0a7d5442ad4a8edbd/raw/2f28d3838d680793280ffe470bcdf9684c743c05/gistfile1.txt" class="external-link" rel="nofollow">https://gist.githubusercontent.com/ckannan/59c0a7d5442ad4a8edbd/raw/2f28d3838d680793280ffe470bcdf9684c743c05/gistfile1.txt</a></p>

<p>cloud-init works normally on GCE</p></comment></comments><attachments>
                    </attachments><subtasks>
                    </subtasks><customfields><customfield id="customfield_10012" key="com.pyxis.greenhopper.jira:gh-lexo-rank"><customfieldname>Rank</customfieldname><customfieldvalues><customfieldvalue>0|i000i7:</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10200" key="com.atlassian.jira.plugin.system.customfieldtypes:select"><customfieldname>Target Milestone</customfieldname><customfieldvalues><customfieldvalue key="10201">CR-2</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10023" key="com.atlassian.bonfire.plugin:bonfire-testing-status-cft"><customfieldname>Testing Status</customfieldname><customfieldvalues></customfieldvalues></customfield><customfield id="customfield_10001" key="com.atlassian.jira.ext.charting:timeinstatus"><customfieldname>[CHART] Time in Status</customfieldname><customfieldvalues></customfieldvalues></customfield></customfields></item><item><title>[CR-61] Switch CR Image creation to use kickstart files as well</title><link>https://cloudrouter.atlassian.net/browse/CR-61</link><project id="10002" key="CR">CloudRouter Project</project><description/><environment/><key id="10201">CR-61</key><summary>Switch CR Image creation to use kickstart files as well</summary><type id="4" iconUrl="https://cloudrouter.atlassian.net/images/icons/issuetypes/improvement.png">Improvement</type><priority id="1" iconUrl="https://cloudrouter.atlassian.net/images/icons/priorities/highest.png">Highest</priority><status id="5" iconUrl="https://cloudrouter.atlassian.net/images/icons/statuses/resolved.png" description="A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.">Resolved</status><statusCategory id="3" key="done" colorName="green"/><resolution id="1">Fixed</resolution><assignee username="ckannan">Chandrasekar Kannan</assignee><reporter username="ckannan">Chandrasekar Kannan</reporter><labels>
                    </labels><created>Thu, 16 Apr 2015 02:02:55 +1000</created><updated>Thu, 2 Jul 2015 04:28:21 +1000</updated><resolved>Thu, 2 Jul 2015 04:28:21 +1000</resolved><component>image</component><due/><votes>0</votes><watches>1</watches><comments><comment id="10605" author="ckannan" created="Sat, 23 May 2015 06:43:24 +1000"><p><a href="https://github.com/cloudrouter/cloudrouter/pull/74" class="external-link" rel="nofollow">https://github.com/cloudrouter/cloudrouter/pull/74</a> submitted</p></comment><comment id="10903" author="ckannan" created="Thu, 2 Jul 2015 04:28:07 +1000"><p><a href="https://github.com/cloudrouter/cloudrouter/pull/94" class="external-link" rel="nofollow">https://github.com/cloudrouter/cloudrouter/pull/94</a><br/>
<a href="https://github.com/cloudrouter/cloudrouter/pull/93" class="external-link" rel="nofollow">https://github.com/cloudrouter/cloudrouter/pull/93</a><br/>
<a href="https://github.com/cloudrouter/cloudrouter/pull/92" class="external-link" rel="nofollow">https://github.com/cloudrouter/cloudrouter/pull/92</a><br/>
<a href="https://github.com/cloudrouter/cloudrouter/pull/87" class="external-link" rel="nofollow">https://github.com/cloudrouter/cloudrouter/pull/87</a><br/>
<a href="https://github.com/cloudrouter/cloudrouter/pull/76" class="external-link" rel="nofollow">https://github.com/cloudrouter/cloudrouter/pull/76</a></p>

<p><img class="emoticon" src="https://cloudrouter.atlassian.net/images/icons/emoticons/smile.gif" height="16" width="16" align="absmiddle" alt="" border="0"/> Done now</p></comment><comment id="10904" author="ckannan" created="Thu, 2 Jul 2015 04:28:21 +1000"><p>per comment above</p></comment></comments><attachments>
                    </attachments><subtasks>
                    </subtasks><customfields><customfield id="customfield_10012" key="com.pyxis.greenhopper.jira:gh-lexo-rank"><customfieldname>Rank</customfieldname><customfieldvalues><customfieldvalue>0|i000if:</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10200" key="com.atlassian.jira.plugin.system.customfieldtypes:select"><customfieldname>Target Milestone</customfieldname><customfieldvalues><customfieldvalue key="10201">CR-2</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10023" key="com.atlassian.bonfire.plugin:bonfire-testing-status-cft"><customfieldname>Testing Status</customfieldname><customfieldvalues></customfieldvalues></customfield><customfield id="customfield_10001" key="com.atlassian.jira.ext.charting:timeinstatus"><customfieldname>[CHART] Time in Status</customfieldname><customfieldvalues></customfieldvalues></customfield></customfields></item><item><title>[CR-64] Upgrade Fedora Base to 21 (or 22 alpha)</title><link>https://cloudrouter.atlassian.net/browse/CR-64</link><project id="10002" key="CR">CloudRouter Project</project><description><p>We need to upgrade the base to F21.</p></description><environment/><key id="10207">CR-64</key><summary>Upgrade Fedora Base to 21 (or 22 alpha)</summary><type id="4" iconUrl="https://cloudrouter.atlassian.net/images/icons/issuetypes/improvement.png">Improvement</type><priority id="1" iconUrl="https://cloudrouter.atlassian.net/images/icons/priorities/highest.png">Highest</priority><status id="6" iconUrl="https://cloudrouter.atlassian.net/images/icons/statuses/closed.png" description="The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.">Closed</status><statusCategory id="3" key="done" colorName="green"/><resolution id="3">Duplicate</resolution><assignee username="jturner">Jay Turner</assignee><reporter username="abn">Arun Neelicattu</reporter><labels>
                    </labels><created>Fri, 17 Apr 2015 12:10:32 +1000</created><updated>Fri, 5 Jun 2015 09:33:53 +1000</updated><resolved>Fri, 5 Jun 2015 09:33:52 +1000</resolved><version>1.0-beta</version><version>1.0</version><component>cloudrouter-release</component><component>Distribution</component><component>image</component><component>kickstart</component><component>OpenDaylight</component><due/><votes>0</votes><watches>3</watches><comments><comment id="10507" author="shainesus" created="Tue, 5 May 2015 09:16:38 +1000"><p>Will be resolved by re-basing w/ F22 which is due to release end of May 2015.</p></comment><comment id="10704" author="jturner" created="Fri, 5 Jun 2015 09:33:53 +1000"><p>Duplicate of <a href="https://cloudrouter.atlassian.net/browse/CR-27" title="Rebase on Fedora 22 once it is available" class="issue-link" data-issue-key="CR-27"><del>CR-27</del></a></p></comment></comments><issuelinks><issuelinktype id="10000"><name>Blocks</name><inwardlinks description="is blocked by"><issuelink><issuekey id="10211">DOCKER-7</issuekey></issuelink></inwardlinks></issuelinktype></issuelinks><attachments>
                    </attachments><subtasks><subtask id="10209">CR-66</subtask></subtasks><customfields><customfield id="customfield_10012" key="com.pyxis.greenhopper.jira:gh-lexo-rank"><customfieldname>Rank</customfieldname><customfieldvalues><customfieldvalue>0|i000jr:</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10200" key="com.atlassian.jira.plugin.system.customfieldtypes:select"><customfieldname>Target Milestone</customfieldname><customfieldvalues><customfieldvalue key="10201">CR-2</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10023" key="com.atlassian.bonfire.plugin:bonfire-testing-status-cft"><customfieldname>Testing Status</customfieldname><customfieldvalues></customfieldvalues></customfield><customfield id="customfield_10000" key="com.atlassian.jira.ext.charting:firstresponsedate"><customfieldname>[CHART] Date of First Response</customfieldname><customfieldvalues><customfieldvalue>Mon, 4 May 2015 16:16:38 -0700</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10001" key="com.atlassian.jira.ext.charting:timeinstatus"><customfieldname>[CHART] Time in Status</customfieldname><customfieldvalues></customfieldvalues></customfield></customfields></item><item><title>[CR-65] Upgrade ODL package to Lithium</title><link>https://cloudrouter.atlassian.net/browse/CR-65</link><project id="10002" key="CR">CloudRouter Project</project><description><p>$</p>
{SUMMARY}</description><environment/><key id="10208">CR-65</key><summary>Upgrade ODL package to Lithium</summary><type id="5" iconUrl="https://cloudrouter.atlassian.net/images/icons/issuetypes/subtask_alternate.png">Sub-task</type><parent id="10033">CR-27</parent><priority id="1" iconUrl="https://cloudrouter.atlassian.net/images/icons/priorities/highest.png">Highest</priority><status id="5" iconUrl="https://cloudrouter.atlassian.net/images/icons/statuses/resolved.png" description="A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.">Resolved</status><statusCategory id="3" key="done" colorName="green"/><resolution id="1">Fixed</resolution><assignee username="jturner">Jay Turner</assignee><reporter username="abn">Arun Neelicattu</reporter><labels>
                    </labels><created>Fri, 17 Apr 2015 12:12:24 +1000</created><updated>Wed, 8 Jul 2015 02:49:38 +1000</updated><resolved>Wed, 8 Jul 2015 02:49:38 +1000</resolved><version>1.0-beta</version><version>1.0</version><component>OpenDaylight</component><due/><votes>0</votes><watches>3</watches><comments><comment id="10206" author="abn" created="Fri, 17 Apr 2015 12:15:13 +1000"><p>We require distribution-karaf-0.3.0-2015-0408 is required at the minimum.</p></comment><comment id="10508" author="shainesus" created="Tue, 5 May 2015 09:16:58 +1000"><p>Will be resolved by re-basing w/ F22 which is due to release end of May 2015.</p></comment><comment id="11008" author="ckannan" created="Wed, 8 Jul 2015 02:49:27 +1000"><p>this is now fixed. resolving.</p></comment></comments><issuelinks><issuelinktype id="10002"><name>Duplicate</name><inwardlinks description="is duplicated by"><issuelink><issuekey id="11000">CR-92</issuekey></issuelink></inwardlinks></issuelinktype><issuelinktype id="10003"><name>Relates</name><inwardlinks description="relates to"><issuelink><issuekey id="11001">CR-93</issuekey></issuelink></inwardlinks></issuelinktype></issuelinks><attachments>
                    </attachments><subtasks>
                    </subtasks><customfields><customfield id="customfield_10012" key="com.pyxis.greenhopper.jira:gh-lexo-rank"><customfieldname>Rank</customfieldname><customfieldvalues><customfieldvalue>0|i000jz:</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10200" key="com.atlassian.jira.plugin.system.customfieldtypes:select"><customfieldname>Target Milestone</customfieldname><customfieldvalues><customfieldvalue key="10201">CR-2</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10023" key="com.atlassian.bonfire.plugin:bonfire-testing-status-cft"><customfieldname>Testing Status</customfieldname><customfieldvalues></customfieldvalues></customfield><customfield id="customfield_10000" key="com.atlassian.jira.ext.charting:firstresponsedate"><customfieldname>[CHART] Date of First Response</customfieldname><customfieldvalues><customfieldvalue>Mon, 4 May 2015 16:16:58 -0700</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10001" key="com.atlassian.jira.ext.charting:timeinstatus"><customfieldname>[CHART] Time in Status</customfieldname><customfieldvalues></customfieldvalues></customfield></customfields></item><item><title>[CR-66] Upgrade cloudrouter-release package to use Fedora 22</title><link>https://cloudrouter.atlassian.net/browse/CR-66</link><project id="10002" key="CR">CloudRouter Project</project><description><p>We need to upgrade the fedora repo versions and GPG keys used in the cloudrouter-release package.</p></description><environment/><key id="10209">CR-66</key><summary>Upgrade cloudrouter-release package to use Fedora 22</summary><type id="5" iconUrl="https://cloudrouter.atlassian.net/images/icons/issuetypes/subtask_alternate.png">Sub-task</type><parent id="10207">CR-64</parent><priority id="1" iconUrl="https://cloudrouter.atlassian.net/images/icons/priorities/highest.png">Highest</priority><status id="5" iconUrl="https://cloudrouter.atlassian.net/images/icons/statuses/resolved.png" description="A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.">Resolved</status><statusCategory id="3" key="done" colorName="green"/><resolution id="1">Fixed</resolution><assignee username="jturner">Jay Turner</assignee><reporter username="abn">Arun Neelicattu</reporter><labels>
                    </labels><created>Fri, 17 Apr 2015 12:14:34 +1000</created><updated>Wed, 8 Jul 2015 02:51:35 +1000</updated><resolved>Wed, 8 Jul 2015 02:51:35 +1000</resolved><version>1.0-beta</version><version>1.0</version><component>cloudrouter-release</component><due/><votes>0</votes><watches>3</watches><comments><comment id="10509" author="shainesus" created="Tue, 5 May 2015 09:17:24 +1000"><p>Will be resolved by re-basing w/ F22 which is due to release end of May 2015.</p></comment><comment id="11009" author="ckannan" created="Wed, 8 Jul 2015 02:51:31 +1000"><p>this is also fixed. resolving</p></comment></comments><attachments>
                    </attachments><subtasks>
                    </subtasks><customfields><customfield id="customfield_10012" key="com.pyxis.greenhopper.jira:gh-lexo-rank"><customfieldname>Rank</customfieldname><customfieldvalues><customfieldvalue>0|i000k7:</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10200" key="com.atlassian.jira.plugin.system.customfieldtypes:select"><customfieldname>Target Milestone</customfieldname><customfieldvalues><customfieldvalue key="10201">CR-2</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10023" key="com.atlassian.bonfire.plugin:bonfire-testing-status-cft"><customfieldname>Testing Status</customfieldname><customfieldvalues></customfieldvalues></customfield><customfield id="customfield_10000" key="com.atlassian.jira.ext.charting:firstresponsedate"><customfieldname>[CHART] Date of First Response</customfieldname><customfieldvalues><customfieldvalue>Mon, 4 May 2015 16:17:24 -0700</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10001" key="com.atlassian.jira.ext.charting:timeinstatus"><customfieldname>[CHART] Time in Status</customfieldname><customfieldvalues></customfieldvalues></customfield></customfields></item><item><title>[CR-67] Update image distributions</title><link>https://cloudrouter.atlassian.net/browse/CR-67</link><project id="10002" key="CR">CloudRouter Project</project><description><p>$SUMMARY</p></description><environment/><key id="10210">CR-67</key><summary>Update image distributions</summary><type id="5" iconUrl="https://cloudrouter.atlassian.net/images/icons/issuetypes/subtask_alternate.png">Sub-task</type><parent id="10033">CR-27</parent><priority id="1" iconUrl="https://cloudrouter.atlassian.net/images/icons/priorities/highest.png">Highest</priority><status id="5" iconUrl="https://cloudrouter.atlassian.net/images/icons/statuses/resolved.png" description="A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.">Resolved</status><statusCategory id="3" key="done" colorName="green"/><resolution id="1">Fixed</resolution><assignee username="jturner">Jay Turner</assignee><reporter username="abn">Arun Neelicattu</reporter><labels>
                    </labels><created>Fri, 17 Apr 2015 12:15:50 +1000</created><updated>Mon, 13 Jul 2015 09:56:47 +1000</updated><resolved>Mon, 13 Jul 2015 09:56:47 +1000</resolved><version>1.0-beta</version><version>1.0</version><component>Distribution</component><component>image</component><due/><votes>0</votes><watches>2</watches><comments><comment id="10510" author="shainesus" created="Tue, 5 May 2015 09:17:47 +1000"><p>Will be resolved by re-basing w/ F22 which is due to release end of May 2015.</p></comment></comments><attachments>
                    </attachments><subtasks>
                    </subtasks><customfields><customfield id="customfield_10012" key="com.pyxis.greenhopper.jira:gh-lexo-rank"><customfieldname>Rank</customfieldname><customfieldvalues><customfieldvalue>0|i000kf:</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10200" key="com.atlassian.jira.plugin.system.customfieldtypes:select"><customfieldname>Target Milestone</customfieldname><customfieldvalues><customfieldvalue key="10201">CR-2</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10023" key="com.atlassian.bonfire.plugin:bonfire-testing-status-cft"><customfieldname>Testing Status</customfieldname><customfieldvalues></customfieldvalues></customfield><customfield id="customfield_10000" key="com.atlassian.jira.ext.charting:firstresponsedate"><customfieldname>[CHART] Date of First Response</customfieldname><customfieldvalues><customfieldvalue>Mon, 4 May 2015 16:17:47 -0700</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10001" key="com.atlassian.jira.ext.charting:timeinstatus"><customfieldname>[CHART] Time in Status</customfieldname><customfieldvalues></customfieldvalues></customfield></customfields></item><item><title>[DOCKER-8] Update Docker base images to be build using kickstart files.</title><link>https://cloudrouter.atlassian.net/browse/DOCKER-8</link><project id="10001" key="DOCKER">CloudRouter Docker</project><description><p>$SUMMARY</p></description><environment/><key id="10212">DOCKER-8</key><summary>Update Docker base images to be build using kickstart files.</summary><type id="5" iconUrl="https://cloudrouter.atlassian.net/images/icons/issuetypes/subtask_alternate.png">Sub-task</type><parent id="10211">DOCKER-7</parent><priority id="1" iconUrl="https://cloudrouter.atlassian.net/images/icons/priorities/highest.png">Highest</priority><status id="5" iconUrl="https://cloudrouter.atlassian.net/images/icons/statuses/resolved.png" description="A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.">Resolved</status><statusCategory id="3" key="done" colorName="green"/><resolution id="1">Fixed</resolution><assignee username="ckannan">Chandrasekar Kannan</assignee><reporter username="abn">Arun Neelicattu</reporter><labels>
                    </labels><created>Fri, 17 Apr 2015 14:20:26 +1000</created><updated>Tue, 14 Jul 2015 04:03:55 +1000</updated><resolved>Tue, 14 Jul 2015 04:03:55 +1000</resolved><due/><votes>0</votes><watches>3</watches><comments><comment id="10512" author="shainesus" created="Tue, 5 May 2015 09:20:26 +1000"><p>To unify build scripts to be done using kickstarts.</p></comment><comment id="11020" author="ckannan" created="Thu, 9 Jul 2015 08:49:59 +1000"><p>Based on this.. <a href="https://github.com/CentOS/sig-cloud-instance-build/tree/master/docker" class="external-link" rel="nofollow">https://github.com/CentOS/sig-cloud-instance-build/tree/master/docker</a> all we need to do is update the Makefile here <a href="https://github.com/cloudrouter/cloudrouter/tree/master/kickstarts" class="external-link" rel="nofollow">https://github.com/cloudrouter/cloudrouter/tree/master/kickstarts</a> and add a new target called 'docker-img' and do the following...</p>

<p>use the *.xz that comes out of the 'virt-img' target and...</p>


<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>virt-tar-out -a cloudrouter-&lt;version&gt;-&lt;os&gt;-&lt;profile&gt;.img / - | xz --best &gt; cloudrouter-version-&lt;os&gt;-&lt;profile&gt;-docker.tar.xz
cat cloudrouter-version-&lt;os&gt;-&lt;profile&gt;-docker.tar.xz | docker import - &lt;container-name&gt;
</pre>
</div></div></comment><comment id="11040" author="ckannan" created="Sat, 11 Jul 2015 11:45:37 +1000"><p><a href="https://github.com/cloudrouter/cloudrouter/pull/110" class="external-link" rel="nofollow">https://github.com/cloudrouter/cloudrouter/pull/110</a></p></comment><comment id="11102" author="ckannan" created="Tue, 14 Jul 2015 03:20:59 +1000"><p><a href="https://github.com/cloudrouter/cloudrouter/pull/113" class="external-link" rel="nofollow">https://github.com/cloudrouter/cloudrouter/pull/113</a></p></comment><comment id="11103" author="ckannan" created="Tue, 14 Jul 2015 03:23:08 +1000"><p>PR # 110 and #113 have been merged now. And the CI build to generate this is now working. We still require a release engineer or someone that has permissions to the dockerhub registry to take the output of this build and submit it. </p></comment><comment id="11106" author="ckannan" created="Tue, 14 Jul 2015 04:03:08 +1000"><p>I launched a CI job and the artifacts are here.</p>

<p><a href="https://ci.cloudrouter.org/job/cloudrouter-image-builder-via-ks/105/" class="external-link" rel="nofollow">https://ci.cloudrouter.org/job/cloudrouter-image-builder-via-ks/105/</a></p>
</comment><comment id="11107" author="ckannan" created="Tue, 14 Jul 2015 04:03:50 +1000"><p>Submitting the artifacts to the registry is tracked separately - <a href="https://cloudrouter.atlassian.net/browse/CR-104" class="external-link" rel="nofollow">https://cloudrouter.atlassian.net/browse/CR-104</a></p></comment></comments><attachments>
                    </attachments><subtasks>
                    </subtasks><customfields><customfield id="customfield_10012" key="com.pyxis.greenhopper.jira:gh-lexo-rank"><customfieldname>Rank</customfieldname><customfieldvalues><customfieldvalue>0|i000kn:</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10200" key="com.atlassian.jira.plugin.system.customfieldtypes:select"><customfieldname>Target Milestone</customfieldname><customfieldvalues><customfieldvalue key="10201">CR-2</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10023" key="com.atlassian.bonfire.plugin:bonfire-testing-status-cft"><customfieldname>Testing Status</customfieldname><customfieldvalues></customfieldvalues></customfield><customfield id="customfield_10000" key="com.atlassian.jira.ext.charting:firstresponsedate"><customfieldname>[CHART] Date of First Response</customfieldname><customfieldvalues><customfieldvalue>Mon, 4 May 2015 16:20:26 -0700</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10001" key="com.atlassian.jira.ext.charting:timeinstatus"><customfieldname>[CHART] Time in Status</customfieldname><customfieldvalues></customfieldvalues></customfield></customfields></item><item><title>[CR-69] Not able to Login After import to VirtualBox</title><link>https://cloudrouter.atlassian.net/browse/CR-69</link><project id="10002" key="CR">CloudRouter Project</project><description/><environment><p>Hi All,</p>

<p>I downloaded the latest cloud-beta-full raw image and converted using raw to vdi file to import the VM into Virtualbox using below command</p>

<p>#VBoxManage convertdd CloudRouter-Beta-Full-20150401.x86_64.raw CloudRouter-Beta-Full-20150401.x86_64.vdi --format VDI</p>

<p>After successful boot I could see the Fedora console. But the issue is I could not able to login using the credentials cloudrouter:CloudRouter. And also tried without password.</p>

<p>I believe in grub you they passed console parameter. Can I know how can I login and use this router. </p>

<p>After Installation how can I proceed if there any document how to use.</p>

</environment><key id="10301">CR-69</key><summary>Not able to Login After import to VirtualBox</summary><type id="1" iconUrl="https://cloudrouter.atlassian.net/images/icons/issuetypes/bug.png">Bug</type><priority id="3" iconUrl="https://cloudrouter.atlassian.net/images/icons/priorities/medium.png">Medium</priority><status id="5" iconUrl="https://cloudrouter.atlassian.net/images/icons/statuses/resolved.png" description="A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.">Resolved</status><statusCategory id="3" key="done" colorName="green"/><resolution id="1">Fixed</resolution><assignee username="jagee">Jeremy Agee</assignee><reporter username="sjkeerthi">Keerthiraja</reporter><labels>
                    </labels><created>Sat, 25 Apr 2015 15:15:50 +1000</created><updated>Tue, 14 Jul 2015 03:03:54 +1000</updated><resolved>Tue, 14 Jul 2015 03:03:54 +1000</resolved><version>1.0-beta</version><fixVersion>2.0-beta</fixVersion><component>Installation</component><due/><votes>0</votes><watches>2</watches><timeestimate seconds="0">0 minutes</timeestimate><timespent seconds="3600">1 hour</timespent><comments><comment id="10400" author="jagee" created="Tue, 28 Apr 2015 07:08:15 +1000"><p>qemu-img convert -f raw -O vmdk cloudrouter-fedora-minimal.raw cloudrouter-fedora-minimal.vmdk<br/>
cp image and cloud-init iso to windows w virtualbox<br/>
create vm attach img and attache cloud-init iso<br/>
boot edit grub<br/>
add in selinux=1 enforcing=0 at the end of the linux line in grub and press F10<br/>
system will boot and load cloudrouter user data from cloud-init. bash is denied and logged during a login in the audit log.</p></comment><comment id="10401" author="jagee" created="Thu, 30 Apr 2015 04:47:45 +1000"><p>The full /var/log dir. The guest was booting with selinux=1 enforcing=0 so it did log denied access but didnt stop the login process.</p></comment><comment id="11101" author="jagee" created="Tue, 14 Jul 2015 03:03:15 +1000"><p>Tested with the cr2 build 101 and virtualbox5.0.0.r101573. cloudrouter boots, loads the cloud-init data and is accessible over ssh via key or password loaded but cloud-init.</p></comment></comments><attachments><attachment id="10000" name="vb-logs.tar.xz" size="200288" author="jagee" created="Thu, 30 Apr 2015 04:46:38 +1000"/></attachments><subtasks>
                    </subtasks><customfields><customfield id="customfield_10012" key="com.pyxis.greenhopper.jira:gh-lexo-rank"><customfieldname>Rank</customfieldname><customfieldvalues><customfieldvalue>0|i000lb:</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10200" key="com.atlassian.jira.plugin.system.customfieldtypes:select"><customfieldname>Target Milestone</customfieldname><customfieldvalues><customfieldvalue key="10201">CR-2</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10023" key="com.atlassian.bonfire.plugin:bonfire-testing-status-cft"><customfieldname>Testing Status</customfieldname><customfieldvalues></customfieldvalues></customfield><customfield id="customfield_10000" key="com.atlassian.jira.ext.charting:firstresponsedate"><customfieldname>[CHART] Date of First Response</customfieldname><customfieldvalues><customfieldvalue>Mon, 27 Apr 2015 14:08:15 -0700</customfieldvalue></customfieldvalues></customfield></customfields></item><item><title>[CR-95] Two packages for capstan</title><link>https://cloudrouter.atlassian.net/browse/CR-95</link><project id="10002" key="CR">CloudRouter Project</project><description><p>  I do see two packages for capstan at <a href="https://repo.cloudrouter.org/fedora/2/x86_64/" class="external-link" rel="nofollow">https://repo.cloudrouter.org/fedora/2/x86_64/</a>. we should clean that up. <br/>
	capstan-0.1.8-1.fc22.x86_64.rpm	2015-07-03 02:04	1.5M	 <br/>
	capstan-0.1.8-1.x86_64.rpm	2015-07-02 05:26	1.5M</p>

<p>Expecting just one. </p></description><environment/><key id="11101">CR-95</key><summary>Two packages for capstan</summary><type id="1" iconUrl="https://cloudrouter.atlassian.net/images/icons/issuetypes/bug.png">Bug</type><priority id="3" iconUrl="https://cloudrouter.atlassian.net/images/icons/priorities/medium.png">Medium</priority><status id="5" iconUrl="https://cloudrouter.atlassian.net/images/icons/statuses/resolved.png" description="A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.">Resolved</status><statusCategory id="3" key="done" colorName="green"/><resolution id="1">Fixed</resolution><assignee username="jturner">Jay Turner</assignee><reporter username="ckannan">Chandrasekar Kannan</reporter><labels>
                    </labels><created>Tue, 7 Jul 2015 04:54:09 +1000</created><updated>Tue, 7 Jul 2015 07:34:55 +1000</updated><resolved>Tue, 7 Jul 2015 07:33:20 +1000</resolved><due/><votes>0</votes><watches>2</watches><comments><comment id="11003" author="jturner" created="Tue, 7 Jul 2015 07:33:20 +1000"><p>I deleted the capstan-0.1.8-1.x86_64.rpm as well as confirmed there was no corresponding SRPMS, and that the repo did not need to be rebuilt (it did not).</p></comment><comment id="11004" author="ckannan" created="Tue, 7 Jul 2015 07:34:55 +1000"><p>I was wondering there might be a script that's producing this....maybe not?</p></comment></comments><attachments>
                    </attachments><subtasks>
                    </subtasks><customfields><customfield id="customfield_10012" key="com.pyxis.greenhopper.jira:gh-lexo-rank"><customfieldname>Rank</customfieldname><customfieldvalues><customfieldvalue>0|i000sv:</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10200" key="com.atlassian.jira.plugin.system.customfieldtypes:select"><customfieldname>Target Milestone</customfieldname><customfieldvalues><customfieldvalue key="10201">CR-2</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10023" key="com.atlassian.bonfire.plugin:bonfire-testing-status-cft"><customfieldname>Testing Status</customfieldname><customfieldvalues></customfieldvalues></customfield><customfield id="customfield_10000" key="com.atlassian.jira.ext.charting:firstresponsedate"><customfieldname>[CHART] Date of First Response</customfieldname><customfieldvalues><customfieldvalue>Mon, 6 Jul 2015 14:33:20 -0700</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10001" key="com.atlassian.jira.ext.charting:timeinstatus"><customfieldname>[CHART] Time in Status</customfieldname><customfieldvalues></customfieldvalues></customfield></customfields></item><item><title>[CR-96] Mininet 2.2.0 rpm packages is missing a whole folder of classes</title><link>https://cloudrouter.atlassian.net/browse/CR-96</link><project id="10002" key="CR">CloudRouter Project</project><description><p>The package "mininet-2.2.0-1.fc22.x86_64.rpm" is missing a directory of classes, which causes mininet to be non-functional (all commands fail because of import errors of the missing classes). </p>

<p>The directory that is missing is here: <a href="https://github.com/mininet/mininet/tree/2.2.0/examples" class="external-link" rel="nofollow">https://github.com/mininet/mininet/tree/2.2.0/examples</a></p>

<p>I verified that after manually downloading that directory, mininet was functional. </p></description><environment><p>CR v2</p></environment><key id="11102">CR-96</key><summary>Mininet 2.2.0 rpm packages is missing a whole folder of classes</summary><type id="1" iconUrl="https://cloudrouter.atlassian.net/images/icons/issuetypes/bug.png">Bug</type><priority id="2" iconUrl="https://cloudrouter.atlassian.net/images/icons/priorities/high.png">High</priority><status id="5" iconUrl="https://cloudrouter.atlassian.net/images/icons/statuses/resolved.png" description="A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.">Resolved</status><statusCategory id="3" key="done" colorName="green"/><resolution id="1">Fixed</resolution><assignee username="jturner">Jay Turner</assignee><reporter username="kkhalasi">kkhalasi</reporter><labels>
                    </labels><created>Tue, 7 Jul 2015 05:14:50 +1000</created><updated>Tue, 7 Jul 2015 08:45:43 +1000</updated><resolved>Tue, 7 Jul 2015 07:07:18 +1000</resolved><due/><votes>0</votes><watches>2</watches><comments><comment id="11002" author="jturner" created="Tue, 7 Jul 2015 07:07:18 +1000"><p><a href="https://github.com/cloudrouter/cloudrouter/pull/100" class="external-link" rel="nofollow">https://github.com/cloudrouter/cloudrouter/pull/100</a></p></comment></comments><attachments><attachment id="10201" name="Screen Shot 2015-07-06 at 12.13.09 PM.png" size="11304" author="kkhalasi" created="Tue, 7 Jul 2015 05:13:43 +1000"/></attachments><subtasks>
                    </subtasks><customfields><customfield id="customfield_10012" key="com.pyxis.greenhopper.jira:gh-lexo-rank"><customfieldname>Rank</customfieldname><customfieldvalues><customfieldvalue>0|i000t3:</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10200" key="com.atlassian.jira.plugin.system.customfieldtypes:select"><customfieldname>Target Milestone</customfieldname><customfieldvalues><customfieldvalue key="10201">CR-2</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10023" key="com.atlassian.bonfire.plugin:bonfire-testing-status-cft"><customfieldname>Testing Status</customfieldname><customfieldvalues></customfieldvalues></customfield><customfield id="customfield_10000" key="com.atlassian.jira.ext.charting:firstresponsedate"><customfieldname>[CHART] Date of First Response</customfieldname><customfieldvalues><customfieldvalue>Mon, 6 Jul 2015 14:07:18 -0700</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10001" key="com.atlassian.jira.ext.charting:timeinstatus"><customfieldname>[CHART] Time in Status</customfieldname><customfieldvalues></customfieldvalues></customfield></customfields></item><item><title>[CR-97] fastnetmon service doesn't come up</title><link>https://cloudrouter.atlassian.net/browse/CR-97</link><project id="10002" key="CR">CloudRouter Project</project><description>
<p>yum install fastnetmon<br/>
systemctl enable fastnetmon<br/>
systemctl start fastnetmon</p>

<p><span class="error">&#91;root@localhost ~&#93;</span># systemctl start fastnetmon<br/>
Job for fastnetmon.service failed. See "systemctl status fastnetmon.service" and "journalctl -xe" for details.<br/>
<span class="error">&#91;root@localhost ~&#93;</span># </p>

<p>Jul 06 15:03:16 localhost.localdomain systemd<span class="error">&#91;1&#93;</span>: Starting FastNetMon - DoS/DDoS analyzer with sflow/netflow/mirror support...<br/>
Jul 06 15:03:16 localhost.localdomain systemd<span class="error">&#91;9180&#93;</span>: Failed at step EXEC spawning /opt/fastnetmon/fastnetmon: No such file or directory<br/>
Jul 06 15:03:16 localhost.localdomain systemd<span class="error">&#91;1&#93;</span>: fastnetmon.service: control process exited, code=exited status=203<br/>
Jul 06 15:03:16 localhost.localdomain systemd<span class="error">&#91;1&#93;</span>: Failed to start FastNetMon - DoS/DDoS analyzer with sflow/netflow/mirror support.<br/>
Jul 06 15:03:16 localhost.localdomain systemd<span class="error">&#91;1&#93;</span>: Unit fastnetmon.service entered failed state.<br/>
Jul 06 15:03:16 localhost.localdomain systemd<span class="error">&#91;1&#93;</span>: fastnetmon.service failed.</p>
</description><environment/><key id="11103">CR-97</key><summary>fastnetmon service doesn't come up</summary><type id="1" iconUrl="https://cloudrouter.atlassian.net/images/icons/issuetypes/bug.png">Bug</type><priority id="2" iconUrl="https://cloudrouter.atlassian.net/images/icons/priorities/high.png">High</priority><status id="5" iconUrl="https://cloudrouter.atlassian.net/images/icons/statuses/resolved.png" description="A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.">Resolved</status><statusCategory id="3" key="done" colorName="green"/><resolution id="1">Fixed</resolution><assignee username="jturner">Jay Turner</assignee><reporter username="ckannan">Chandrasekar Kannan</reporter><labels>
                    </labels><created>Tue, 7 Jul 2015 08:07:11 +1000</created><updated>Tue, 7 Jul 2015 11:15:52 +1000</updated><resolved>Tue, 7 Jul 2015 11:15:52 +1000</resolved><due/><votes>0</votes><watches>3</watches><comments><comment id="11005" author="jturner" created="Tue, 7 Jul 2015 09:31:11 +1000"><p>The systemd .service file which is included in the tarball needs to be more flexible to different distros, as currently it hard-codes /opt/fastnetmon/fastnetmon as the location of the binary.  In order to not disturb the pristine tarball, patches the fastnetmon.service file in the spec file, while awaiting a proper fix upstream.  <a href="https://github.com/cloudrouter/cloudrouter/pull/101" class="external-link" rel="nofollow">https://github.com/cloudrouter/cloudrouter/pull/101</a></p></comment><comment id="11007" author="dfj" created="Tue, 7 Jul 2015 11:15:52 +1000"><p>PR was cherry picked to master.</p></comment></comments><attachments>
                    </attachments><subtasks>
                    </subtasks><customfields><customfield id="customfield_10012" key="com.pyxis.greenhopper.jira:gh-lexo-rank"><customfieldname>Rank</customfieldname><customfieldvalues><customfieldvalue>0|i000tb:</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10200" key="com.atlassian.jira.plugin.system.customfieldtypes:select"><customfieldname>Target Milestone</customfieldname><customfieldvalues><customfieldvalue key="10201">CR-2</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10023" key="com.atlassian.bonfire.plugin:bonfire-testing-status-cft"><customfieldname>Testing Status</customfieldname><customfieldvalues></customfieldvalues></customfield><customfield id="customfield_10000" key="com.atlassian.jira.ext.charting:firstresponsedate"><customfieldname>[CHART] Date of First Response</customfieldname><customfieldvalues><customfieldvalue>Mon, 6 Jul 2015 16:31:11 -0700</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10001" key="com.atlassian.jira.ext.charting:timeinstatus"><customfieldname>[CHART] Time in Status</customfieldname><customfieldvalues></customfieldvalues></customfield></customfields></item><item><title>[CR-98] postrun error in cloudrouter onos package</title><link>https://cloudrouter.atlassian.net/browse/CR-98</link><project id="10002" key="CR">CloudRouter Project</project><description><p>18:45:12 INFO | Removing the ONOS package: groupdel: group 'onos' does not exist<br/>
warning: %postun(onos-1.2.1-1.fc22.noarch) scriptlet failed, exit status 6</p></description><environment/><key id="11104">CR-98</key><summary>postrun error in cloudrouter onos package</summary><type id="1" iconUrl="https://cloudrouter.atlassian.net/images/icons/issuetypes/bug.png">Bug</type><priority id="3" iconUrl="https://cloudrouter.atlassian.net/images/icons/priorities/medium.png">Medium</priority><status id="5" iconUrl="https://cloudrouter.atlassian.net/images/icons/statuses/resolved.png" description="A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.">Resolved</status><statusCategory id="3" key="done" colorName="green"/><resolution id="1">Fixed</resolution><assignee username="jturner">Jay Turner</assignee><reporter username="jagee">Jeremy Agee</reporter><labels>
                    </labels><created>Tue, 7 Jul 2015 08:55:18 +1000</created><updated>Tue, 7 Jul 2015 09:52:44 +1000</updated><resolved>Tue, 7 Jul 2015 09:52:44 +1000</resolved><due/><votes>0</votes><watches>2</watches><comments><comment id="11006" author="jturner" created="Tue, 7 Jul 2015 09:52:44 +1000"><p><a href="https://github.com/cloudrouter/cloudrouter/pull/102" class="external-link" rel="nofollow">https://github.com/cloudrouter/cloudrouter/pull/102</a></p></comment></comments><attachments>
                    </attachments><subtasks>
                    </subtasks><customfields><customfield id="customfield_10012" key="com.pyxis.greenhopper.jira:gh-lexo-rank"><customfieldname>Rank</customfieldname><customfieldvalues><customfieldvalue>0|i000tj:</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10200" key="com.atlassian.jira.plugin.system.customfieldtypes:select"><customfieldname>Target Milestone</customfieldname><customfieldvalues><customfieldvalue key="10201">CR-2</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10023" key="com.atlassian.bonfire.plugin:bonfire-testing-status-cft"><customfieldname>Testing Status</customfieldname><customfieldvalues></customfieldvalues></customfield><customfield id="customfield_10000" key="com.atlassian.jira.ext.charting:firstresponsedate"><customfieldname>[CHART] Date of First Response</customfieldname><customfieldvalues><customfieldvalue>Mon, 6 Jul 2015 16:52:44 -0700</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10001" key="com.atlassian.jira.ext.charting:timeinstatus"><customfieldname>[CHART] Time in Status</customfieldname><customfieldvalues></customfieldvalues></customfield></customfields></item><item><title>[CR-99] CR v2 builds do not have any -beta tag</title><link>https://cloudrouter.atlassian.net/browse/CR-99</link><project id="10002" key="CR">CloudRouter Project</project><description><p>CR v2 builds aren't tagged -beta. </p>

<p><span class="error">&#91;1&#93;</span> Image names<br/>
<span class="error">&#91;2&#93;</span> repo with -beta tag<br/>
<span class="error">&#91;3&#93;</span> builds with -beta tag. </p>

<p>What else?</p></description><environment/><key id="11105">CR-99</key><summary>CR v2 builds do not have any -beta tag</summary><type id="1" iconUrl="https://cloudrouter.atlassian.net/images/icons/issuetypes/bug.png">Bug</type><priority id="1" iconUrl="https://cloudrouter.atlassian.net/images/icons/priorities/highest.png">Highest</priority><status id="5" iconUrl="https://cloudrouter.atlassian.net/images/icons/statuses/resolved.png" description="A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.">Resolved</status><statusCategory id="3" key="done" colorName="green"/><resolution id="1">Fixed</resolution><assignee username="jturner">Jay Turner</assignee><reporter username="ckannan">Chandrasekar Kannan</reporter><labels>
                    </labels><created>Thu, 9 Jul 2015 04:09:29 +1000</created><updated>Sat, 11 Jul 2015 03:51:30 +1000</updated><resolved>Sat, 11 Jul 2015 03:51:30 +1000</resolved><due/><votes>0</votes><watches>3</watches><comments><comment id="11011" author="ckannan" created="Thu, 9 Jul 2015 04:10:22 +1000"><p>any relevant documentation with -beta tag?</p></comment><comment id="11012" author="shainesus" created="Thu, 9 Jul 2015 04:16:48 +1000"><p>Header at first login via console should also be modified.</p>

<p><a id="10202_thumb" href="https://cloudrouter.atlassian.net/secure/attachment/10202/10202_Screenshot6.jpg" title="Screenshot6.jpg"><img src="https://cloudrouter.atlassian.net/secure/thumbnail/10202/_thumb_10202.png" align="absmiddle" border="0" /></a></p></comment><comment id="11014" author="ckannan" created="Thu, 9 Jul 2015 05:52:55 +1000"><p>that's older builds though</p></comment><comment id="11015" author="ckannan" created="Thu, 9 Jul 2015 05:53:36 +1000"><p>newer builds say this</p>


<p>CloudRouter release 2 (CloudRouter)<br/>
Kernel 4.0.5-300.fc22.x86_64 on an x86_64 (ttyS0)</p>

<p>localhost login: </p></comment><comment id="11016" author="jturner" created="Thu, 9 Jul 2015 05:53:42 +1000"><p>Noting that the screenshot which Scott attached <b>is</b> running CRv1 Beta . . . still need to verify the right content is showing for v2 Beta.</p></comment><comment id="11018" author="shainesus" created="Thu, 9 Jul 2015 07:41:59 +1000"><p>I realize its a shot of the older build.  I was using it as an example of what we need to ensure to include in the header with this newer build.</p></comment><comment id="11031" author="ckannan" created="Sat, 11 Jul 2015 03:47:43 +1000"><p>CI builds  #100 and #101 do mention beta now.</p>


<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
CloudRouter release 2 (CloudRouter Beta)
Kernel 4.0.5-300.fc22.x86_64 on an x86_64 (ttyS0)

CloudRouter login: cloudRouter

</pre>
</div></div></comment></comments><attachments><attachment id="10202" name="Screenshot6.jpg" size="82222" author="shaines" created="Thu, 9 Jul 2015 04:15:37 +1000"/><attachment id="10203" name="Screenshot from 2015-07-10 10-49-36.png" size="54348" author="ckannan" created="Sat, 11 Jul 2015 03:50:15 +1000"/></attachments><subtasks>
                    </subtasks><customfields><customfield id="customfield_10012" key="com.pyxis.greenhopper.jira:gh-lexo-rank"><customfieldname>Rank</customfieldname><customfieldvalues><customfieldvalue>0|i000tr:</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10200" key="com.atlassian.jira.plugin.system.customfieldtypes:select"><customfieldname>Target Milestone</customfieldname><customfieldvalues><customfieldvalue key="10201">CR-2</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10023" key="com.atlassian.bonfire.plugin:bonfire-testing-status-cft"><customfieldname>Testing Status</customfieldname><customfieldvalues></customfieldvalues></customfield><customfield id="customfield_10000" key="com.atlassian.jira.ext.charting:firstresponsedate"><customfieldname>[CHART] Date of First Response</customfieldname><customfieldvalues><customfieldvalue>Wed, 8 Jul 2015 11:16:48 -0700</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10001" key="com.atlassian.jira.ext.charting:timeinstatus"><customfieldname>[CHART] Time in Status</customfieldname><customfieldvalues></customfieldvalues></customfield></customfields></item><item><title>[CR-100] 'build-components.sh' incorrectly filtering build artifacts</title><link>https://cloudrouter.atlassian.net/browse/CR-100</link><project id="10002" key="CR">CloudRouter Project</project><description><p>As it stands now the build-components.sh script is moving components based on the basename of the package . . . which is bad for stuff like python-exabgp which produces both "python-exabgp" and "exabgp" artifacts.  Net result the exabgp package does not get moved, and does not appear as an artifact in Jenkins.  Let's just pick-up all of the *.rpm artifacts and move them instead.  </p>

<p>diff --git a/build/rpms/build-components.sh b/build/rpms/build-components.sh<br/>
index 74c2148..2eb1e24 100755<br/>
&#8212; a/build/rpms/build-components.sh<br/>
+++ b/build/rpms/build-components.sh<br/>
@@ -64,7 +64,7 @@ for COMPONENT in "$</p>
{COMPONENTS[@]}
<p>"; do<br/>
             -exec rpmbuild "$</p>
{RPM_BUILD_OPTS[@]}
<p>" --clean {} \; | tee $</p>
{LOG_FILE}

<ol>
	<li>lets pull out the rpms created</li>
</ol>
<ul class="alternate" type="square">
	<li>find $
{RPM_BUILD_RPMS} -name "${COMPONENT}*.rpm" \<br/>
+        find ${RPM_BUILD_RPMS}
<p> -name "*.rpm" \<br/>
             -exec mv {} . \;<br/>
         find $</p>
{RPM_BUILD_SRPMS}
<p> -name "$</p>
{COMPONENT}
<p>*.rpm" \<br/>
             -exec mv {} . \;</p></li>
</ul>
</description><environment/><key id="11106">CR-100</key><summary>'build-components.sh' incorrectly filtering build artifacts</summary><type id="1" iconUrl="https://cloudrouter.atlassian.net/images/icons/issuetypes/bug.png">Bug</type><priority id="2" iconUrl="https://cloudrouter.atlassian.net/images/icons/priorities/high.png">High</priority><status id="5" iconUrl="https://cloudrouter.atlassian.net/images/icons/statuses/resolved.png" description="A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.">Resolved</status><statusCategory id="3" key="done" colorName="green"/><resolution id="1">Fixed</resolution><assignee username="jturner">Jay Turner</assignee><reporter username="jturner">Jay Turner</reporter><labels>
                    </labels><created>Thu, 9 Jul 2015 05:04:45 +1000</created><updated>Fri, 10 Jul 2015 23:11:42 +1000</updated><resolved>Fri, 10 Jul 2015 23:11:42 +1000</resolved><component>Build</component><due/><votes>0</votes><watches>2</watches><comments><comment id="11021" author="ckannan" created="Fri, 10 Jul 2015 02:31:54 +1000"><p>Is here a pull request for this ?</p></comment><comment id="11022" author="jturner" created="Fri, 10 Jul 2015 04:21:42 +1000"><p>I thought I pushed it yesterday, but does not seem that I did.  Will do so here shortly.</p></comment><comment id="11023" author="jturner" created="Fri, 10 Jul 2015 04:57:11 +1000"><p><a href="https://github.com/cloudrouter/cloudrouter/pull/107" class="external-link" rel="nofollow">https://github.com/cloudrouter/cloudrouter/pull/107</a></p></comment><comment id="11024" author="ckannan" created="Fri, 10 Jul 2015 05:03:40 +1000"><p>done</p></comment><comment id="11026" author="jturner" created="Fri, 10 Jul 2015 23:11:42 +1000"><p>And confirmed.  Closing.</p></comment></comments><attachments>
                    </attachments><subtasks>
                    </subtasks><customfields><customfield id="customfield_10012" key="com.pyxis.greenhopper.jira:gh-lexo-rank"><customfieldname>Rank</customfieldname><customfieldvalues><customfieldvalue>0|i000tz:</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10200" key="com.atlassian.jira.plugin.system.customfieldtypes:select"><customfieldname>Target Milestone</customfieldname><customfieldvalues><customfieldvalue key="10201">CR-2</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10023" key="com.atlassian.bonfire.plugin:bonfire-testing-status-cft"><customfieldname>Testing Status</customfieldname><customfieldvalues></customfieldvalues></customfield><customfield id="customfield_10000" key="com.atlassian.jira.ext.charting:firstresponsedate"><customfieldname>[CHART] Date of First Response</customfieldname><customfieldvalues><customfieldvalue>Thu, 9 Jul 2015 09:31:54 -0700</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10001" key="com.atlassian.jira.ext.charting:timeinstatus"><customfieldname>[CHART] Time in Status</customfieldname><customfieldvalues></customfieldvalues></customfield></customfields></item><item><title>[CR-103] Require additional CloudRouter version numbers added to JIRA</title><link>https://cloudrouter.atlassian.net/browse/CR-103</link><project id="10002" key="CR">CloudRouter Project</project><description><p>Hey Jay,</p>

<p>Writing to request we add CloudRouter versions 2.0 (e.g. '2.0') and v2.0 BETA (e.g. '2.0-beta') to the "Affects Version/s" and "Fix Version/s" fields in JIRA.</p>

<p>Thanks.</p>

<p>~ Scott</p></description><environment/><key id="11110">CR-103</key><summary>Require additional CloudRouter version numbers added to JIRA</summary><type id="3" iconUrl="https://cloudrouter.atlassian.net/images/icons/issuetypes/task.png">Task</type><priority id="3" iconUrl="https://cloudrouter.atlassian.net/images/icons/priorities/medium.png">Medium</priority><status id="6" iconUrl="https://cloudrouter.atlassian.net/images/icons/statuses/closed.png" description="The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.">Closed</status><statusCategory id="3" key="done" colorName="green"/><resolution id="1">Fixed</resolution><assignee username="jturner">Jay Turner</assignee><reporter username="shaines">Scott Haines</reporter><labels>
                    </labels><created>Sun, 12 Jul 2015 02:41:12 +1000</created><updated>Tue, 14 Jul 2015 02:28:59 +1000</updated><resolved>Tue, 14 Jul 2015 02:28:59 +1000</resolved><version>2.0</version><version>2.0-beta</version><fixVersion>2.0</fixVersion><fixVersion>2.0-beta</fixVersion><due>Fri, 17 Jul 2015 00:00:00 -0700</due><votes>0</votes><watches>2</watches><comments><comment id="11100" author="jturner" created="Tue, 14 Jul 2015 02:28:59 +1000"><p>Done.  "2.0" and "2.0-beta" added to both the "Affects Version/s" and "Fix Version/s" drop-downs.</p></comment></comments><attachments>
                    </attachments><subtasks>
                    </subtasks><customfields><customfield id="customfield_10012" key="com.pyxis.greenhopper.jira:gh-lexo-rank"><customfieldname>Rank</customfieldname><customfieldvalues><customfieldvalue>0|i000uv:</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10200" key="com.atlassian.jira.plugin.system.customfieldtypes:select"><customfieldname>Target Milestone</customfieldname><customfieldvalues><customfieldvalue key="10201">CR-2</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10023" key="com.atlassian.bonfire.plugin:bonfire-testing-status-cft"><customfieldname>Testing Status</customfieldname><customfieldvalues></customfieldvalues></customfield><customfield id="customfield_10000" key="com.atlassian.jira.ext.charting:firstresponsedate"><customfieldname>[CHART] Date of First Response</customfieldname><customfieldvalues><customfieldvalue>Mon, 13 Jul 2015 09:28:59 -0700</customfieldvalue></customfieldvalues></customfield><customfield id="customfield_10001" key="com.atlassian.jira.ext.charting:timeinstatus"><customfieldname>[CHART] Time in Status</customfieldname><customfieldvalues></customfieldvalues></customfield></customfields></item></channel></rss>
